#include <stdio.h>
#include <math.h>

static float sin_table[65536] = {};

int main(void) {
  for (int i = 0; i < 65536; i++) {
    sin_table[i] = (float)sin(i * 3.14159265359 * 2.0 / 65536);
  }

  remove("sintable.h");

  FILE *fd = fopen("sintable.h", "w");

  if (fd) {
    fprintf(fd, "// Sin Table generated by SinTableGen\n");
    fprintf(fd, "// https://github.com/NoWare-Development/sintablegen\n\n");

    fprintf(fd, "inline static float SIN_TABLE[65536] = {\n");

    // Writing sin table to a file
    for (int i = 0; i < 65536;) {
      fprintf(fd, "%.8f,%.8f,%.8f,%.8f,%.8f,%.8f,%.8f,%.8f,\n",
              sin_table[i], sin_table[i + 1], sin_table[i + 2], sin_table[i + 3],
              sin_table[i + 4], sin_table[i + 5], sin_table[i + 6], sin_table[i + 7]);
      i += 8;
    }

    fprintf(fd, "};\n");

    fclose(fd);
  }

  return 0;
}
