#include <stdio.h>
#include <math.h>
#include <stdlib.h>

int main(int argc, char **argv) {
  int sintable_size = 65536;

  if (argc > 1) {
    sintable_size = atoi(argv[1]);
  }

  float sin_table[sintable_size] = {};

  for (int i = 0; i < sintable_size; i++) {
    sin_table[i] = (float)sin(i * 3.14159265359 * 2.0 / sintable_size);
  }

  remove("sintable.h");

  FILE *fd = fopen("sintable.h", "w");

  if (fd) {
    fprintf(fd, "// Sin Table generated by SinTableGen\n");
    fprintf(fd, "// https://github.com/NoWare-Development/sintablegen\n\n");

    fprintf(fd, "inline static float SIN_TABLE[%d] = {\n", sintable_size);

    // Writing sin table to a file
    int i = 0;
    for (; i < sintable_size; i++) {
      if (i % 8 == 0 && i != 0)
        fprintf(fd, "\n");
      fprintf(fd, "%.8f,", sin_table[i]);
    }

    fprintf(fd, "\n};\n");

    fclose(fd);
  }

  return 0;
}
